import { Patient, db } from '../utils/db';
import { useLiveQuery } from 'dexie-react-hooks';
import { 
  User, Settings, Phone, Pill, Bell, Globe, Download, Share2, LogOut, Heart, MessageCircle, ChevronRight, Check
} from 'lucide-react';
import { cn } from '../lib/utils';
import { useState } from 'react';
import BottomSheet from '../components/BottomSheet';

export default function Profile({ patient }: { patient: Patient }) {
  const readings = useLiveQuery(() => db.readings.toArray());
  const lastReading = readings?.sort((a, b) => b.timestamp - a.timestamp)[0];
  const [activeSetting, setActiveSetting] = useState<'reminder' | 'language' | null>(null);
  const [showResetConfirm, setShowResetConfirm] = useState(false);

  const shareOnWhatsApp = () => {
    if (!lastReading) {
      const generalText = `گلوکو برج — پاکستان میں شوگر کے مریضوں کی مددگار ایپ۔ استعمال کریں اور اپنی صحت کا خیال رکھیں۔`;
      window.open(`https://wa.me/?text=${encodeURIComponent(generalText)}`, '_blank');
      return;
    }
    const text = `میری آج کی شوگر ریڈنگ: ${lastReading.value} mg/dL | Status: ${lastReading.triageStatus} | Generated by GlucoBridge — گلوکو برج`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const handleNativeShare = async () => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'GlucoBridge',
          text: 'Check out GlucoBridge - the diabetes management app for Pakistan!',
          url: window.location.origin
        });
      } else {
        copyToClipboard();
      }
    } catch (err) {
      console.error('Error sharing:', err);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText('Check out GlucoBridge - the diabetes management app for Pakistan!');
    alert('Link copied to clipboard!');
  };

  const handleReset = async () => {
    try {
      await db.readings.clear();
      await db.chatHistory.clear();
      await db.patients.clear();
      window.location.reload();
    } catch (err) {
      console.error('Reset failed:', err);
    }
  };

  const updatePatient = async (updates: Partial<Patient>) => {
    if (patient.id) {
      await db.patients.update(patient.id, updates);
      setActiveSetting(null);
    }
  };

  return (
    <div className="pb-8">
      {/* Profile Header */}
      <div className="bg-gradient-to-br from-teal-600 to-teal-700 p-8 rounded-b-[50px] shadow-lg flex flex-col items-center text-white mb-8">
        <div className="w-24 h-24 bg-white/20 rounded-full border-4 border-white/30 flex items-center justify-center text-4xl font-bold mb-4 backdrop-blur-sm shadow-xl">
          {patient.name?.charAt(0) || 'U'}
        </div>
        <h2 className="text-2xl font-bold mb-1">{patient.name}</h2>
        <p className="font-urdu opacity-80">{patient.city}, پاکستان</p>
      </div>

      <div className="px-6 space-y-6">
        {/* Settings Group 1 */}
        <section className="bg-white rounded-[30px] border border-slate-100 shadow-sm overflow-hidden">
          <div className="p-4 border-b border-slate-50 flex items-center justify-between">
            <span className="text-[10px] font-bold text-[#9390b9] uppercase tracking-widest">Personal Info</span>
            <User className="h-4 w-4 text-slate-300" />
          </div>
          <div className="divide-y divide-slate-50">
            <ProfileRow icon={Pill} label="Diabetes Type" value={patient.diabetesType} />
            <ProfileRow icon={Phone} label="Emergency Contact" value={patient.emergencyContact} />
            <div className="p-4 flex items-center gap-4">
              <Settings className="h-5 w-5 text-slate-400" />
              <div className="flex-grow">
                <span className="text-xs text-slate-400 block">Medications</span>
                <div className="flex flex-wrap gap-1 mt-1">
                  {patient.medications.map(m => (
                    <span key={m} className="px-2 py-0.5 bg-teal-50 text-teal-600 text-[10px] font-bold rounded-md">{m}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Settings Group 2 */}
        <section className="bg-white rounded-[30px] border border-slate-100 shadow-sm overflow-hidden">
          <div className="p-4 border-b border-slate-50 flex items-center justify-between">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Preferences</span>
            <Settings className="h-4 w-4 text-slate-300" />
          </div>
          <div className="divide-y divide-slate-50">
            <button 
              onClick={() => setActiveSetting('reminder')}
              className="w-full text-left transition-colors hover:bg-slate-50"
            >
              <ProfileRow icon={Bell} label="Reminders" value={patient.reminderTime} hasArrow />
            </button>
            <button 
              onClick={() => setActiveSetting('language')}
              className="w-full text-left transition-colors hover:bg-slate-50"
            >
              <ProfileRow icon={Globe} label="Language" value={patient.language === 'ur' ? 'اردو (Urdu)' : 'English'} hasArrow />
            </button>
          </div>
        </section>

        {/* Social Sharing */}
        <div className="flex gap-4">
          <button 
            onClick={shareOnWhatsApp}
            className="flex-grow bg-[#25D366] text-white py-4 rounded-2xl flex items-center justify-center gap-3 font-bold shadow-lg shadow-[#25D366]/20 active:scale-95 transition-all"
          >
            <MessageCircle className="h-5 w-5" />
            WhatsApp
          </button>
          <button 
            onClick={handleNativeShare}
            className="bg-slate-100 text-slate-600 p-4 rounded-2xl active:bg-slate-200 transition-colors"
          >
            <Share2 className="h-5 w-5" />
          </button>
        </div>

        {/* Danger Zone */}
        {!showResetConfirm ? (
          <button 
            onClick={() => setShowResetConfirm(true)}
            className="w-full py-4 text-red-500 font-bold border-2 border-red-500/10 bg-red-50/50 rounded-2xl flex items-center justify-center gap-2 active:bg-red-100 transition-colors"
          >
            <LogOut className="h-5 w-5" />
            Reset App Data
          </button>
        ) : (
          <div className="flex gap-2">
            <button 
              onClick={handleReset}
              className="flex-[2] py-4 bg-red-600 text-white font-bold rounded-2xl active:bg-red-700 transition-colors"
            >
              Confirm Reset
            </button>
            <button 
              onClick={() => setShowResetConfirm(false)}
              className="flex-1 py-4 bg-slate-100 text-slate-500 font-bold rounded-2xl active:bg-slate-200 transition-colors"
            >
              Cancel
            </button>
          </div>
        )}

        <footer className="text-center py-8">
          <div className="flex justify-center items-center gap-2 text-slate-300 mb-2">
            <span className="h-px w-8 bg-slate-100"></span>
            <Heart className="h-4 w-4 fill-slate-100" />
            <span className="h-px w-8 bg-slate-100"></span>
          </div>
          <p className="text-xs text-slate-400 font-medium">Made with ❤️ for Pakistan</p>
          <p className="text-[10px] text-slate-300 mt-1 uppercase tracking-widest font-bold">GlucoBridge v1.0</p>
        </footer>
      </div>

      {/* Settings Bottom Sheets */}
      <BottomSheet 
        isOpen={activeSetting === 'reminder'} 
        onClose={() => setActiveSetting(null)} 
        title="REMINDER TIME" 
        titleUrdu="یاد دہانی کا وقت"
      >
        <div className="p-6 space-y-4">
          {['08:00 AM', '09:00 AM', '10:00 AM', '08:00 PM', '09:00 PM', '10:00 PM'].map(time => (
            <button
              key={time}
              onClick={() => updatePatient({ reminderTime: time })}
              className={cn(
                "w-full p-4 rounded-2xl border flex justify-between items-center transition-all",
                patient.reminderTime === time ? "border-teal-500 bg-teal-50" : "border-slate-100 bg-white"
              )}
            >
              <span className="font-bold text-slate-700">{time}</span>
              {patient.reminderTime === time && <Check className="h-5 w-5 text-teal-600" />}
            </button>
          ))}
        </div>
      </BottomSheet>

      <BottomSheet 
        isOpen={activeSetting === 'language'} 
        onClose={() => setActiveSetting(null)} 
        title="LANGUAGE" 
        titleUrdu="زبان"
      >
        <div className="p-6 grid grid-cols-1 gap-4">
          <button
            onClick={() => updatePatient({ language: 'ur' })}
            className={cn(
              "p-6 rounded-3xl border flex flex-col items-center gap-2 transition-all",
              patient.language === 'ur' ? "border-teal-500 bg-teal-50" : "border-slate-100 bg-white"
            )}
          >
            <span className="text-2xl">🇵🇰</span>
            <span className="font-bold font-urdu text-lg">اردو (Urdu)</span>
            {patient.language === 'ur' && <Check className="h-5 w-5 text-teal-600" />}
          </button>
          <button
            onClick={() => updatePatient({ language: 'en' })}
            className={cn(
              "p-6 rounded-3xl border flex flex-col items-center gap-2 transition-all",
              patient.language === 'en' ? "border-teal-500 bg-teal-50" : "border-slate-100 bg-white"
            )}
          >
            <span className="text-2xl">🇬🇧</span>
            <span className="font-bold text-lg">English</span>
            {patient.language === 'en' && <Check className="h-5 w-5 text-teal-600" />}
          </button>
        </div>
      </BottomSheet>
    </div>
  );
}

const ProfileRow = ({ icon: Icon, label, value, hasArrow }: { icon: any, label: string, value: string, hasArrow?: boolean }) => (
  <div className="p-4 flex items-center gap-4">
    <Icon className="h-5 w-5 text-slate-400" />
    <div className="flex-grow">
      <span className="text-xs text-slate-400 block">{label}</span>
      <span className="text-sm font-bold text-slate-700">{value}</span>
    </div>
    {hasArrow && <ChevronRight className="h-4 w-4 text-slate-300" />}
  </div>
);
